require 'rails_helper'

RSpec.describe 'Movie' do
  it 'exists and has a poster and a title' do
    details_data = {
      "adult": false,
      "backdrop_path": '/5h8VtV4oh2qkO8Iqz7gypIYJPAr.jpg',
      "belongs_to_collection": nil,
      "budget": 3_300_000,
      "genres": [
        {
          "id": 18,
          "name": 'Drama'
        },
        {
          "id": 10_402,
          "name": 'Music'
        }
      ],
      "homepage": 'http://sonyclassics.com/whiplash/',
      "id": 244_786,
      "imdb_id": 'tt2582802',
      "original_language": 'en',
      "original_title": 'Whiplash',
      "overview": 'Under the direction of a ruthless instructor, a talented young drummer begins to pursue perfection at any cost, even his humanity.',
      "popularity": 58.816,
      "poster_path": '/oPxnRhyAIzJKGUEdSiwTJQBa3NM.jpg',
      "production_companies": [
        {
          "id": 2266,
          "logo_path": '/owzVs2mguyyJ3vIn7EbgowpUPnk.png',
          "name": 'Bold Films',
          "origin_country": 'US'
        },
        {
          "id": 3172,
          "logo_path": '/kDedjRZwO8uyFhuHamomOhN6fzG.png',
          "name": 'Blumhouse Productions',
          "origin_country": 'US'
        },
        {
          "id": 32_157,
          "logo_path": '/4hOCk25Ce8s242NItnwtV7aKRWY.png',
          "name": 'Right of Way Films',
          "origin_country": 'US'
        }
      ],
      "production_countries": [
        {
          "iso_3166_1": 'US',
          "name": 'United States of America'
        }
      ],
      "release_date": '2014-10-10',
      "revenue": 13_092_000,
      "runtime": 107,
      "spoken_languages": [
        {
          "english_name": 'English',
          "iso_639_1": 'en',
          "name": 'English'
        }
      ],
      "status": 'Released',
      "tagline": 'The road to greatness can take you to the edge.',
      "title": 'Whiplash',
      "video": false,
      "vote_average": 8.37,
      "vote_count": 12_477
    }

    reviews_data = {
      "id": 244_786,
      "page": 1,
      "results": [
        {
          "author": 'MJM',
          "author_details": {
            "name": '',
            "username": 'MJM',
            "avatar_path": nil,
            "rating": nil
          },
          "content": "DISGUSTING NONSENSE...\r\n\r\n*** This review may contain spoilers ***\r\n\r\nI find it very sad that so many people - including so-called professional reviewers - have rated this crap so highly. I did not walk out (although I was greatly tempted to do so) but saw it to the end. A total waste of time.\r\n\r\nHere's what might spoil it for you, should you believe the BS that's being spread around this stinking pile of excrement: It could have actually been OK if it hadn't been so laughably impossibly ridiculous. Perhaps if it had been set in the fifties or the forties when people had much less developed consciousness of human rights? But even so... \r\n\r\nI suppose the moral/lesson we are supposed to learn is... if you can't warp your students enough by abuse to force them to become great musicians then it is perfectly alright to discard or destroy them in the attempt. \r\n\r\nThis glorified tyrant and bully can himself only produce music at a grade one level and so because he cannot 'do' he 'teaches?'\r\n\r\nHe does not teach, he does not inspire; he withholds approval, negatively reinforces and rules by fear, and is feared rather than respected. I would have a difficult time to point to a single (pedagogical) scene in the film that had any merit whatsoever or was worth watching for any reason. Maybe I should say that its evident popularity may be evidence that we are truly living in the end times... ha! \r\n\r\nSee the film if you want to be current, but please decide for yourself from watching it and don't believe the hype about its 'genius' or 'brilliance.' It is not either of those things; it's a poorly written, sad joke. \r\n\r\nI would expect that those people who rate it so highly A) want to seem cool because 'it's about jazz' B) have never actually been in a teacher/student situation and therefore, can only imagine how its done C) see all the other positive reviews and so must follow the herd D) don't really know their ass from their elbow or E) thought the the actor had truly grown because in Spiderman he only yell, but it THIS one, he throws chairs.... or F) all of the above.\r\n\r\nSave your money or see something uplifting instead rather than this horseshit.",
          "created_at": '2015-01-28T00:32:03.188Z',
          "id": '54c82e03c3a36870ba000a3d',
          "updated_at": '2021-06-23T15:57:31.798Z',
          "url": 'https://www.themoviedb.org/review/54c82e03c3a36870ba000a3d'
        },
        {
          "author": 'Andres Gomez',
          "author_details": {
            "name": 'Andres Gomez',
            "username": 'tanty',
            "avatar_path": '/https://www.gravatar.com/avatar/03a53cd53b8254fe582d4fe1acc26c4e.jpg',
            "rating": 9.0
          },
          "content": "Fantastic movie with a good cast with an impressive Miles Teller and a yet even more impressive J.K. Simmons. Decent script, great directing, selection of the repertoire and performances.\r\n\r\nJust sit down, get a good audio system and enjoy one of the best movies of the 2010s.",
          "created_at": '2016-01-29T08:42:52.869Z',
          "id": '56ab260cc3a3681c54001f8a',
          "updated_at": '2021-06-23T15:57:44.837Z',
          "url": 'https://www.themoviedb.org/review/56ab260cc3a3681c54001f8a'
        },
        {
          "author": 'DanDare',
          "author_details": {
            "name": '',
            "username": 'DanDare',
            "avatar_path": '/gY0Mjm4thleETxdESQPabdn5CB3.jpg',
            "rating": 5.0
          },
          "content": "J K Simmons won an Oscar for Best Supporting Actor for his mean, bullying monster. Jazz teacher Terence Fletcher who abhors the words 'good job.'\r\n\r\nFletcher tells a tale about Charlie Parker and how doing a good job was not enough for him. Good job means mediocrity.\r\n\r\nYet Fletcher is a mediocre educator and his college seems not to have noticed this. Instead of being an inspiration his students fear him. He is a nasty tyrant and an incident from his past comes back to haunt him.\r\n\r\nMiles Teller plays Andrew Neiman the put upon jazz drummer in the Shaffer Conservatory in New York. Neiman is eager to impress Fletcher but nothing he can do is good enough and withstands all the effluent Fletcher throws at him until one day he snaps.\r\n\r\nDamien Chazelle unleashed an unethical monster in Fletcher with Neiman providing the film's heart but I am not convinced that this is a good film. The rest of the students in the class are silent to the abuse taking place right in front of them. They are young adults, not kids and they do nothing about it.",
          "created_at": '2017-02-26T22:12:37.085Z',
          "id": '58b352d5c3a368525400c173',
          "updated_at": '2021-06-23T15:57:55.133Z',
          "url": 'https://www.themoviedb.org/review/58b352d5c3a368525400c173'
        },
        {
          "author": 'mattwilde123',
          "author_details": {
            "name": '',
            "username": 'mattwilde123',
            "avatar_path": '/wCTsgKvihctPGp4Ms7Y373baeHm.jpg',
            "rating": 9.0
          },
          "content": "When I sat down to watch this film, I didn't know what to expect. I am not usually a fan of films about musicians but this was a brilliant and tense masterpiece. The story is of a very ambitious boy named Andrew (played by Miles Teller) who is a music student in New York. He aspires to be noticed by a prestigious music teacher named Fletcher (played by J.K. Simmons). As his wish starts becoming a reality, he realises the brutality of this teacher who continually pushes him with questionable methods. Damien Chazelle's direction is almost of a tense boxing or war action drama in that it constantly uses the music of the drumming to build the tension whilst using violent and sharp editing whilst the jazz band play.\r\n\r\nChazelle's screenplay is very well written. It is filled with humour, tension and heartbreak. The way in which Fletcher switches during Andrew's first lesson is expertly done. Fletcher relentlessly insults Andrew in a very shocking way which really creates a huge sense of sympathy for Andrew's character as he struggles to respond. The insulting dialogue is very similar to Stanley Kubrick's 'Full Metal Jacket' in that it is both humourous and disturbingly distressing.\r\n\r\nThe performances in this film are remarkable. Miles Teller is a relative newcomer but takes to this character with so much depth and understanding. The drumming scenes look like incredible and torturous workouts and Teller really shows the pain and agony his character is going through to reach his dream. The chemistry between the two central characters is flawless. J.K. Simmons is perfect as the abusive music teacher. Simmons manages to combine Fletcher's distinguished persona with his terrifying unpredictability. Simmons reminds me of his character in Valve's 'Portal 2' in which he continuously spouts insults at the player in a darkly hilarious way.\r\n\r\nOverall, 'Whiplash' is a fascinating study of passion, ambition and love. The film asks questions about the morality of getting one's dreams and the acceptable methods of acquiring them. Full of amazing performances all around, and created with such intensity and spirit, my final rating for this film is 4.5 stars.\r\n\r\n★★★★½",
          "created_at": '2017-03-09T12:47:22.897Z',
          "id": '58c14edac3a368265b009826',
          "updated_at": '2021-06-23T15:57:55.388Z',
          "url": 'https://www.themoviedb.org/review/58c14edac3a368265b009826'
        },
        {
          "author": 'Matthew Brady',
          "author_details": {
            "name": 'Matthew Brady',
            "username": 'MatthewL.Brady',
            "avatar_path": '/k5J0l25FXOCw4TcX6iWaJmYpCZ4.jpg',
            "rating": 10.0
          },
          "content": "\"There are no two words in the English language more harmful than good job\".\r\n\r\nWhiplash follows are main character Andrew Neyman who is a young jazz drummer, single-minded in his pursuit to rise to the top of his elite east coast music conservatory. Plagued by the failed writing career of his father, Andrew hungers day and night to become one of the greats. Terence Fletcher, an instructor equally known for his teaching talents as for his terrifying methods, leads the top jazz ensemble in the school. Fletcher discovers Andrew and transfers the aspiring drummer into his band, forever changing the young man's life.\r\n\r\nOK let me just start off with this. You had no idea how much I was really looking forward to Whiplash. This was on my movies to check out list, because I heard nothing but positive things from this movie and I heard a lot of people described this film has the \"Full Metal Jacket\" but with no war or guns, but with music and well... drums. I think Whiplash and \"Birdman\" was the two movies I wanted to see before making my best movies of the year list, because who knows they might make the list. I haven't seen \"Birdman\" yet but will do soon, but I finally had the chance to see Whiplash and my god this movie was just so spectacularly flawless in many ways. Whiplash is the best move of 2014.\r\n\r\nJ.K. Simmons in this movie probably pulls of the best performance in his career. Every word that came out of his mouth didn't feel like he was reading from the script then act it out. I felt every angry punch of words that came out of him, because it was so real. I didn't see J.K. Simmons just playing a movie character in this movie, no he was the freaking Fletcher.\r\n\r\nNow let's talk about Terence Fletcher: The best way to describe Fletcher to those who haven't seen the film yet, well his like Sgt. Hartman from \"Full Metal Jacket\". When he's on screen your locked on and he's also the kind of person that would be somebody's worse nightmare to have for a boss. This guy doesn't just like music, he breaths music and he wants his band to do perfect. His opinion and his look on music is another thing why I didn't flat out just hated him, I actually understood him. He made a very good point about how people will comment on you act and say \"You did a good job\", and yes I did use the words \"you did a great job\", in my past reviews but now I'm never going to use it ever again after this movie.\r\n\r\nMiles Teller was another stand out performances in this movie, and just like \"Foxcatacher\" where Channing Tatum was so over looked by his performance, well Miles Teller has proved himself to be more then a teen in a movie that will be forgotten and so would he, but no Miles Teller played this character so brilliantly he could become the next big thing. Now his character in this movie has the love of the true art of music and you can see that he wants to tell people his love for music, but when the harsh life of reality comes crashing into him it's truly heartbreaking to see his struggle and effort just not being good enough. Teller played this character so realistic and so brilliantly flawless.\r\n\r\nThe directing and the writing in this was just....perfect. Damien Chazelle gave this movie style and passion to tell a story about two strong music buffs battling out and he freaking nailed it.\r\n\r\nThis movie also had probably the best finale that I've seen in years. My nails were digging into the seat. I didn't dare to look away not for one moment, not for one second. I was simply locked on and when it was over... I'm kidding you I actually clapped towards the end of this movie. Now the biggest cliche that I always hear from critics when their talk about a different movies and their use words like \"You will clap at the end\", but you don't, or \"You will feel inspired after the film\", and I you don't. But Whiplash actually did make me feel inspirited towards the end and made me clap. It's message of not giving up and the dream that you been chancing for isn't just going to come to you. Movies like Pride, freedom Writers and all that such never ever give me that inspiring feeling inside of me, until I watched this movie.\r\n\r\nOverall rating: Whiplash is a movie that everybody needs to see. This isn't just a popcorn movie where you come and put you legs up and laugh a couple of times, no this movie reaches out to people out there that have the same problems that these character's have, with their passion of what their what to do in life get's over shadowed by something you don't want to do and this movie get's it right. So go and see if you have the chance.",
          "created_at": '2020-01-27T18:23:18.593Z',
          "id": '5e2f2a96326c1900121c0682',
          "updated_at": '2021-06-23T15:58:33.525Z',
          "url": 'https://www.themoviedb.org/review/5e2f2a96326c1900121c0682'
        }
      ],
      "total_pages": 1,
      "total_results": 5
    }

    credits_data = {
      "id": 244_786,
      "cast": [
        {
          "adult": false,
          "gender": 2,
          "id": 996_701,
          "known_for_department": 'Acting',
          "name": 'Miles Teller',
          "original_name": 'Miles Teller',
          "popularity": 158.808,
          "profile_path": '/cg3LW0xX6RKr8dmescxq1bepcb5.jpg',
          "cast_id": 5,
          "character": 'Andrew Neiman',
          "credit_id": '52fe4ef7c3a36847f82b3fc3',
          "order": 0
        },
        {
          "adult": false,
          "gender": 2,
          "id": 18_999,
          "known_for_department": 'Acting',
          "name": 'J.K. Simmons',
          "original_name": 'J.K. Simmons',
          "popularity": 55.038,
          "profile_path": '/7kIiPojgSVNRXb5z0hiijcD5LJ6.jpg',
          "cast_id": 6,
          "character": 'Terence Fletcher',
          "credit_id": '52fe4ef7c3a36847f82b3fc7',
          "order": 1
        },
        {
          "adult": false,
          "gender": 2,
          "id": 781,
          "known_for_department": 'Acting',
          "name": 'Paul Reiser',
          "original_name": 'Paul Reiser',
          "popularity": 19.94,
          "profile_path": '/v3e5TClep4ugMdU4qSRiKbvLr3B.jpg',
          "cast_id": 15,
          "character": 'Jim Neiman',
          "credit_id": '5466cd46eaeb817274000acb',
          "order": 2
        },
        {
          "adult": false,
          "gender": 1,
          "id": 129_104,
          "known_for_department": 'Acting',
          "name": 'Melissa Benoist',
          "original_name": 'Melissa Benoist',
          "popularity": 30.34,
          "profile_path": '/tmJsadF5ujTypPZtO54HsXTup3J.jpg',
          "cast_id": 11,
          "character": 'Nicole',
          "credit_id": '52fe4ef7c3a36847f82b3fe3',
          "order": 3
        },
        {
          "adult": false,
          "gender": 2,
          "id": 970_216,
          "known_for_department": 'Acting',
          "name": 'Austin Stowell',
          "original_name": 'Austin Stowell',
          "popularity": 18.708,
          "profile_path": '/At09XQpVXnChgedNsxu4ceR5W9i.jpg',
          "cast_id": 12,
          "character": 'Ryan Connolly',
          "credit_id": '52fe4ef7c3a36847f82b3fe7',
          "order": 4
        },
        {
          "adult": false,
          "gender": 2,
          "id": 15_824,
          "known_for_department": 'Acting',
          "name": 'Chris Mulkey',
          "original_name": 'Chris Mulkey',
          "popularity": 6.059,
          "profile_path": '/tt4kCAovGtaU4pRI4KJfKvTJ8tq.jpg',
          "cast_id": 23,
          "character": 'Uncle Frank',
          "credit_id": '5525415fc3a3687df80016c4',
          "order": 5
        },
        {
          "adult": false,
          "gender": 0,
          "id": 1_451_540,
          "known_for_department": 'Acting',
          "name": 'Nate Lang',
          "original_name": 'Nate Lang',
          "popularity": 5.82,
          "profile_path": '/6TC0gKxJIttIhXLnCttANV9gd1G.jpg',
          "cast_id": 22,
          "character": 'Carl Tanner',
          "credit_id": '5525414d925141720c001b56',
          "order": 6
        },
        {
          "adult": false,
          "gender": 0,
          "id": 1_451_542,
          "known_for_department": 'Acting',
          "name": 'Charlie Ian',
          "original_name": 'Charlie Ian',
          "popularity": 3.746,
          "profile_path": '/5ondXm5m2LoC7sdXhTziNAmuDfw.jpg',
          "cast_id": 27,
          "character": 'Dustin',
          "credit_id": '552541959251415c7c00bd61',
          "order": 7
        },
        {
          "adult": false,
          "gender": 2,
          "id": 223_012,
          "known_for_department": 'Acting',
          "name": 'Jayson Blair',
          "original_name": 'Jayson Blair',
          "popularity": 2.915,
          "profile_path": '/zUMEMibklFznVD2kkpbNTs63UVX.jpg',
          "cast_id": 13,
          "character": 'Travis',
          "credit_id": '52fe4ef7c3a36847f82b3feb',
          "order": 8
        },
        {
          "adult": false,
          "gender": 1,
          "id": 159_366,
          "known_for_department": 'Acting',
          "name": 'Kavita Patil',
          "original_name": 'Kavita Patil',
          "popularity": 2.27,
          "profile_path": '/iDnY0MDtHM6NZPADnGryCbaOVjj.jpg',
          "cast_id": 14,
          "character": 'Sophie',
          "credit_id": '52fe4ef7c3a36847f82b3fef',
          "order": 9
        },
        {
          "adult": false,
          "gender": 2,
          "id": 53_454,
          "known_for_department": 'Acting',
          "name": 'Damon Gupton',
          "original_name": 'Damon Gupton',
          "popularity": 4.17,
          "profile_path": '/bbbJiEx01uvOCKwiEHv9OmPI4r8.jpg',
          "cast_id": 24,
          "character": 'Mr. Kramer',
          "credit_id": '5525416c9251417276001927',
          "order": 10
        },
        {
          "adult": false,
          "gender": 1,
          "id": 1_212_459,
          "known_for_department": 'Acting',
          "name": 'Suanne Spoke',
          "original_name": 'Suanne Spoke',
          "popularity": 4.706,
          "profile_path": '/c3eHskplBRwuORgUWSwnsi6KZpV.jpg',
          "cast_id": 25,
          "character": 'Aunt Emma',
          "credit_id": '55254179c3a3687ded0016cf',
          "order": 11
        },
        {
          "adult": false,
          "gender": 2,
          "id": 52_939,
          "known_for_department": 'Acting',
          "name": 'Max Kasch',
          "original_name": 'Max Kasch',
          "popularity": 2.626,
          "profile_path": '/7BvCZldRpYB4UxJv5IxNSMSYgoe.jpg',
          "cast_id": 26,
          "character": 'Dorm Neighbor',
          "credit_id": '552541869251417be200a8f2',
          "order": 12
        },
        {
          "adult": false,
          "gender": 2,
          "id": 1_451_543,
          "known_for_department": 'Acting',
          "name": 'Kofi Siriboe',
          "original_name": 'Kofi Siriboe',
          "popularity": 8.707,
          "profile_path": '/uJXuRtPvTlrAfwdVGCziOOXr0N8.jpg',
          "cast_id": 29,
          "character": 'Bassist (Nassau)',
          "credit_id": '552541ae925141720c001b71',
          "order": 13
        },
        {
          "adult": false,
          "gender": 0,
          "id": 1_451_545,
          "known_for_department": 'Acting',
          "name": 'C.J. Vana',
          "original_name": 'C.J. Vana',
          "popularity": 3.079,
          "profile_path": '/b8Dql6EEshNGOGXlmIsnVRi8B8B.jpg',
          "cast_id": 31,
          "character": 'Metz',
          "credit_id": '552541c7c3a3687e08001774',
          "order": 14
        },
        {
          "adult": false,
          "gender": 0,
          "id": 171_766,
          "known_for_department": 'Acting',
          "name": 'Tarik Lowe',
          "original_name": 'Tarik Lowe',
          "popularity": 2.526,
          "profile_path": '/7p4fPwQPe2jwdCqEOaIakka8MGD.jpg',
          "cast_id": 32,
          "character": 'Pianist (Studio Band)',
          "credit_id": '55e6d136c3a3685f85002956',
          "order": 15
        },
        {
          "adult": false,
          "gender": 0,
          "id": 1_398_714,
          "known_for_department": 'Acting',
          "name": 'Tyler Kimball',
          "original_name": 'Tyler Kimball',
          "popularity": 1.264,
          "profile_path": '/l7Th75VBqIYPLs9cmztTMFNF9S0.jpg',
          "cast_id": 33,
          "character": 'Saxophonist #2 (Studio Band)',
          "credit_id": '55e6d136c3a3685f98002c48',
          "order": 16
        },
        {
          "adult": false,
          "gender": 2,
          "id": 1_503_721,
          "known_for_department": 'Acting',
          "name": 'Rogelio Douglas Jr.',
          "original_name": 'Rogelio Douglas Jr.',
          "popularity": 2.073,
          "profile_path": '/exzQXahpDJ45McnnuuxT3ynBwQm.jpg',
          "cast_id": 34,
          "character": 'Trumpeter #1 (Studio Band)',
          "credit_id": '55e6d136c3a3685f8e002617',
          "order": 17
        },
        {
          "adult": false,
          "gender": 0,
          "id": 1_503_834,
          "known_for_department": 'Acting',
          "name": 'Adrian Burks',
          "original_name": 'Adrian Burks',
          "popularity": 1.018,
          "profile_path": '/hnidFJRRPEgXAH7ntB8iDZ9GPmj.jpg',
          "cast_id": 35,
          "character": 'Trumpeter #2 (Studio Band)',
          "credit_id": '55e6d137c3a3685f9100272e',
          "order": 18
        },
        {
          "adult": false,
          "gender": 0,
          "id": 1_503_835,
          "known_for_department": 'Acting',
          "name": 'Joseph Bruno',
          "original_name": 'Joseph Bruno',
          "popularity": 0.6,
          "profile_path": nil,
          "cast_id": 36,
          "character": 'Technician (Overbrook) - Mike',
          "credit_id": '55e6d1379251410f0a0026b6',
          "order": 19
        },
        {
          "adult": false,
          "gender": 2,
          "id": 1_296_849,
          "known_for_department": 'Acting',
          "name": 'Michael D. Cohen',
          "original_name": 'Michael D. Cohen',
          "popularity": 5.809,
          "profile_path": '/eEs2yjMUQnmIvwPx66bhL4f55eI.jpg',
          "cast_id": 37,
          "character": 'Stage Hand (Overbrook)',
          "credit_id": '55e6d1379251410f0d002526',
          "order": 20
        },
        {
          "adult": false,
          "gender": 1,
          "id": 1_098_246,
          "known_for_department": 'Acting',
          "name": 'Jocelyn Ayanna',
          "original_name": 'Jocelyn Ayanna',
          "popularity": 0.669,
          "profile_path": '/rIBzNIQcoA7ILHf5mj9j2j2Vk49.jpg',
          "cast_id": 38,
          "character": 'Passerby (Bus Station)',
          "credit_id": '55e6d1389251410f10002836',
          "order": 21
        },
        {
          "adult": false,
          "gender": 2,
          "id": 1_503_836,
          "known_for_department": 'Acting',
          "name": 'Keenan Henson',
          "original_name": 'Keenan Henson',
          "popularity": 2.446,
          "profile_path": '/g9jHx4LxRwN73eFoz1npO5j8IGV.jpg',
          "cast_id": 39,
          "character": 'Truck Driver',
          "credit_id": '55e6d1389251410f0700274e',
          "order": 22
        },
        {
          "adult": false,
          "gender": 0,
          "id": 1_503_837,
          "known_for_department": 'Acting',
          "name": 'Janet Hoskins',
          "original_name": 'Janet Hoskins',
          "popularity": 0.729,
          "profile_path": '/Ab9wA1GipllwMV63t3IlNOfR77S.jpg',
          "cast_id": 40,
          "character": 'Passerby (Dunellen)',
          "credit_id": '55e6d138c3a3685f8e00261a',
          "order": 23
        },
        {
          "adult": false,
          "gender": 1,
          "id": 10_691,
          "known_for_department": 'Acting',
          "name": 'April Grace',
          "original_name": 'April Grace',
          "popularity": 5.373,
          "profile_path": '/nV8nnymN0ClT3xppwhlAtUnjSxa.jpg',
          "cast_id": 41,
          "character": 'Rachel Bornholdt',
          "credit_id": '55e6d138c3a3685f91002733',
          "order": 24
        },
        {
          "adult": false,
          "gender": 0,
          "id": 1_503_838,
          "known_for_department": 'Acting',
          "name": "Clifton 'Fou Fou' Eddie",
          "original_name": "Clifton 'Fou Fou' Eddie",
          "popularity": 0.6,
          "profile_path": '/jIxkjRSTGvfnr06zVRHeOk3uDsb.jpg',
          "cast_id": 42,
          "character": 'Drummer (Quartet)',
          "credit_id": '55e6d139c3a3685f98002c4c',
          "order": 25
        },
        {
          "adult": false,
          "gender": 2,
          "id": 1_145_677,
          "known_for_department": 'Acting',
          "name": 'Calvin C. Winbush',
          "original_name": 'Calvin C. Winbush',
          "popularity": 0.6,
          "profile_path": '/m62DdAXKrWwQrarmJxPy0H4mKLz.jpg',
          "cast_id": 43,
          "character": 'Saxophonist',
          "credit_id": '55e6d22f9251410f1300293a',
          "order": 26
        },
        {
          "adult": false,
          "gender": 2,
          "id": 1_291_961,
          "known_for_department": 'Acting',
          "name": 'Marcus Henderson',
          "original_name": 'Marcus Henderson',
          "popularity": 2.192,
          "profile_path": '/vTevIy7GKjhmpoAhoayifnwqgn2.jpg',
          "cast_id": 44,
          "character": 'Bassist (JVC)',
          "credit_id": '55e6d22fc3a3685f98002c83',
          "order": 27
        },
        {
          "adult": false,
          "gender": 0,
          "id": 1_503_841,
          "known_for_department": 'Acting',
          "name": 'Tony Baker',
          "original_name": 'Tony Baker',
          "popularity": 0.84,
          "profile_path": '/48jzlzMUOHSGO1umjhZlU65mapZ.jpg',
          "cast_id": 45,
          "character": 'Stage Hand (Carnegie Hall)',
          "credit_id": '55e6d2309251410f17002943',
          "order": 28
        },
        {
          "adult": false,
          "gender": 2,
          "id": 16_506,
          "known_for_department": 'Acting',
          "name": 'Henry G. Sanders',
          "original_name": 'Henry G. Sanders',
          "popularity": 6.203,
          "profile_path": '/4HWUP5K5kPxt5c0Xp65QOyV5gPG.jpg',
          "cast_id": 46,
          "character": 'Red Henderson',
          "credit_id": '55e6d230c3a3685f96002a6b',
          "order": 29
        },
        {
          "adult": false,
          "gender": 0,
          "id": 1_503_842,
          "known_for_department": 'Acting',
          "name": 'Sam Campisi',
          "original_name": 'Sam Campisi',
          "popularity": 0.98,
          "profile_path": nil,
          "cast_id": 47,
          "character": 'Andrew (8 years old)',
          "credit_id": '55e6d2309251410f0a0026e0',
          "order": 30
        },
        {
          "adult": false,
          "gender": 0,
          "id": 1_503_843,
          "known_for_department": 'Acting',
          "name": 'Jimmie Kirkpatrick',
          "original_name": 'Jimmie Kirkpatrick',
          "popularity": 0.6,
          "profile_path": nil,
          "cast_id": 48,
          "character": 'Nassau Trumpeter #2',
          "credit_id": '55e6d231c3a3685f96002a6e',
          "order": 31
        },
        {
          "adult": false,
          "gender": 0,
          "id": 1_503_844,
          "known_for_department": 'Acting',
          "name": 'Keenan Allen',
          "original_name": 'Keenan Allen',
          "popularity": 0.694,
          "profile_path": nil,
          "cast_id": 49,
          "character": 'Studio Core Member #1',
          "credit_id": '55e6d2319251410f040027d9',
          "order": 32
        },
        {
          "adult": false,
          "gender": 0,
          "id": 1_503_845,
          "known_for_department": 'Acting',
          "name": 'Ayinde Vaughan',
          "original_name": 'Ayinde Vaughan',
          "popularity": 0.6,
          "profile_path": nil,
          "cast_id": 50,
          "character": 'Studio Core Member #2',
          "credit_id": '55e6d2319251410f17002948',
          "order": 33
        },
        {
          "adult": false,
          "gender": 0,
          "id": 1_435_768,
          "known_for_department": 'Acting',
          "name": 'Shai Golan',
          "original_name": 'Shai Golan',
          "popularity": 0.6,
          "profile_path": nil,
          "cast_id": 51,
          "character": 'Studio Core Member #3',
          "credit_id": '55e6d231c3a3685f96002a72',
          "order": 34
        },
        {
          "adult": false,
          "gender": 0,
          "id": 1_503_846,
          "known_for_department": 'Acting',
          "name": 'Yancey Wells',
          "original_name": 'Yancey Wells',
          "popularity": 0.6,
          "profile_path": nil,
          "cast_id": 52,
          "character": 'Studio Core Member #4',
          "credit_id": '55e6d2329251410f1300293d',
          "order": 35
        },
        {
          "adult": false,
          "gender": 0,
          "id": 1_503_847,
          "known_for_department": 'Acting',
          "name": 'Candace Roberge',
          "original_name": 'Candace Roberge',
          "popularity": 0.6,
          "profile_path": nil,
          "cast_id": 53,
          "character": 'Student #1',
          "credit_id": '55e6d232c3a3685f98002c86',
          "order": 36
        },
        {
          "adult": false,
          "gender": 0,
          "id": 1_503_848,
          "known_for_department": 'Acting',
          "name": 'Krista Kilber',
          "original_name": 'Krista Kilber',
          "popularity": 0.6,
          "profile_path": nil,
          "cast_id": 54,
          "character": 'Student #2',
          "credit_id": '55e6d2329251410f13002943',
          "order": 37
        },
        {
          "adult": false,
          "gender": 2,
          "id": 1_503_853,
          "known_for_department": 'Acting',
          "name": 'Stephen Hsu',
          "original_name": 'Stephen Hsu',
          "popularity": 0.6,
          "profile_path": nil,
          "cast_id": 59,
          "character": 'JVC Guitarist (uncredited)',
          "credit_id": '55e6d234c3a3685f98002c8c',
          "order": 38
        },
        {
          "adult": false,
          "gender": 2,
          "id": 1_503_854,
          "known_for_department": 'Acting',
          "name": 'Herman Johansen',
          "original_name": 'Herman Johansen',
          "popularity": 0.6,
          "profile_path": nil,
          "cast_id": 60,
          "character": 'Music Competition Judge (uncredited)',
          "credit_id": '55e6d234c3a3685f9100275a',
          "order": 39
        },
        {
          "adult": false,
          "gender": 1,
          "id": 79_051,
          "known_for_department": 'Acting',
          "name": 'Wendee Lee',
          "original_name": 'Wendee Lee',
          "popularity": 3.177,
          "profile_path": '/ojPHjXFtUhh7PlBNAAu0fiv5h5z.jpg',
          "cast_id": 61,
          "character": 'Audience Member (uncredited)',
          "credit_id": '55e6d234c3a3685f9e002777',
          "order": 40
        },
        {
          "adult": false,
          "gender": 2,
          "id": 1_360_008,
          "known_for_department": 'Acting',
          "name": 'Joseph Oliveira',
          "original_name": 'Joseph Oliveira',
          "popularity": 3.347,
          "profile_path": '/hrVn7CVgShz3UaLLnzMxSIRnKCa.jpg',
          "cast_id": 65,
          "character": 'Bartender (uncredited)',
          "credit_id": '55e6d2369251410f0d002555',
          "order": 41
        },
        {
          "adult": false,
          "gender": 1,
          "id": 81_380,
          "known_for_department": 'Acting',
          "name": 'Michelle Ruff',
          "original_name": 'Michelle Ruff',
          "popularity": 1.388,
          "profile_path": '/wO6VvUeVRlVm2N4lutsz6ayBxL5.jpg',
          "cast_id": 66,
          "character": 'Audience Member (uncredited)',
          "credit_id": '55e6d236c3a3685f9e002779',
          "order": 42
        },
        {
          "adult": false,
          "gender": 2,
          "id": 1_503_858,
          "known_for_department": 'Sound',
          "name": 'Daniel Weidlein',
          "original_name": 'Daniel Weidlein',
          "popularity": 0.6,
          "profile_path": nil,
          "cast_id": 67,
          "character": 'Studio Band Saxophone Player (uncredited)',
          "credit_id": '55e6d2369251410f0d002558',
          "order": 43
        }
      ],
      "crew": [
        {
          "adult": false,
          "gender": 1,
          "id": 494,
          "known_for_department": 'Production',
          "name": 'Terri Taylor',
          "original_name": 'Terri Taylor',
          "popularity": 1.27,
          "profile_path": nil,
          "credit_id": '54d5356ec3a3683ba0000039',
          "department": 'Production',
          "job": 'Casting'
        },
        {
          "adult": false,
          "gender": 2,
          "id": 6745,
          "known_for_department": 'Sound',
          "name": 'Richard Henderson',
          "original_name": 'Richard Henderson',
          "popularity": 0.6,
          "profile_path": nil,
          "credit_id": '56407fa89251417055000b58',
          "department": 'Sound',
          "job": 'Music Editor'
        },
        {
          "adult": false,
          "gender": 2,
          "id": 9250,
          "known_for_department": 'Production',
          "name": 'Jeffrey Stott',
          "original_name": 'Jeffrey Stott',
          "popularity": 1.976,
          "profile_path": nil,
          "credit_id": '5789212392514135d60025fd',
          "department": 'Production',
          "job": 'Executive In Charge Of Production'
        },
        {
          "adult": false,
          "gender": 0,
          "id": 23_783,
          "known_for_department": 'Costume & Make-Up',
          "name": 'Heather Plott',
          "original_name": 'Heather Plott',
          "popularity": 0.6,
          "profile_path": nil,
          "credit_id": '57892074c3a36835fa002886',
          "department": 'Costume & Make-Up',
          "job": 'Makeup Artist'
        },
        {
          "adult": false,
          "gender": 0,
          "id": 23_786,
          "known_for_department": 'Costume & Make-Up',
          "name": 'Nacoma Whobrey',
          "original_name": 'Nacoma Whobrey',
          "popularity": 1.284,
          "profile_path": nil,
          "credit_id": '56408055925141705c000bee',
          "department": 'Costume & Make-Up',
          "job": 'Makeup Department Head'
        },
        {
          "adult": false,
          "gender": 2,
          "id": 53_181,
          "known_for_department": 'Camera',
          "name": 'Sharone Meir',
          "original_name": 'Sharone Meir',
          "popularity": 0.6,
          "profile_path": nil,
          "credit_id": '52fe4ef7c3a36847f82b3fb9',
          "department": 'Camera',
          "job": 'Director of Photography'
        },
        {
          "adult": false,
          "gender": 2,
          "id": 52_443,
          "known_for_department": 'Directing',
          "name": 'Jason Reitman',
          "original_name": 'Jason Reitman',
          "popularity": 6.657,
          "profile_path": '/eNNN1dwfB6b6p2hoEG1xyoa7H2p.jpg',
          "credit_id": '56407e4ac3a3685059000c7c',
          "department": 'Production',
          "job": 'Executive Producer'
        },
        {
          "adult": false,
          "gender": 1,
          "id": 113_045,
          "known_for_department": 'Sound',
          "name": 'Dawn Lunsford',
          "original_name": 'Dawn Lunsford',
          "popularity": 3.065,
          "profile_path": '/gaGtvXaFT7hZzGc12KsYp91etlh.jpg',
          "credit_id": '5b0c05529251411dca013ac5',
          "department": 'Sound',
          "job": 'Foley Artist'
        },
        {
          "adult": false,
          "gender": 2,
          "id": 60_864,
          "known_for_department": 'Production',
          "name": 'David Lancaster',
          "original_name": 'David Lancaster',
          "popularity": 1.4,
          "profile_path": '/bBTYGOWuF3WJBgiqVSpNBuL9qlg.jpg',
          "credit_id": '52fe4ef7c3a36847f82b3fd9',
          "department": 'Production',
          "job": 'Producer'
        },
        {
          "adult": false,
          "gender": 0,
          "id": 66_726,
          "known_for_department": 'Production',
          "name": 'Michel Litvak',
          "original_name": 'Michel Litvak',
          "popularity": 0.6,
          "profile_path": nil,
          "credit_id": '52fe4ef7c3a36847f82b3fdf',
          "department": 'Production',
          "job": 'Producer'
        },
        {
          "adult": false,
          "gender": 2,
          "id": 66_727,
          "known_for_department": 'Production',
          "name": 'Gary Michael Walters',
          "original_name": 'Gary Michael Walters',
          "popularity": 1.506,
          "profile_path": '/tz0JL10EVQiGUSqtveiRDJjq6c2.jpg',
          "credit_id": '56407e8b9251417052000c80',
          "department": 'Production',
          "job": 'Executive Producer'
        },
        {
          "adult": false,
          "gender": 2,
          "id": 84_348,
          "known_for_department": 'Production',
          "name": 'Jason Blum',
          "original_name": 'Jason Blum',
          "popularity": 4.248,
          "profile_path": '/9tm1oUdA6HOUaaS4bwWI2ihmBVt.jpg',
          "credit_id": '52fe4ef7c3a36847f82b3fcd',
          "department": 'Production',
          "job": 'Producer'
        },
        {
          "adult": false,
          "gender": 2,
          "id": 136_495,
          "known_for_department": 'Writing',
          "name": 'Damien Chazelle',
          "original_name": 'Damien Chazelle',
          "popularity": 4.915,
          "profile_path": '/14kRZ3XxNMyBv717YQSXr3wCucy.jpg',
          "credit_id": '52fe4ef7c3a36847f82b3fad',
          "department": 'Directing',
          "job": 'Director'
        },
        {
          "adult": false,
          "gender": 2,
          "id": 136_495,
          "known_for_department": 'Writing',
          "name": 'Damien Chazelle',
          "original_name": 'Damien Chazelle',
          "popularity": 4.915,
          "profile_path": '/14kRZ3XxNMyBv717YQSXr3wCucy.jpg',
          "credit_id": '629baca1992fe60050b3f306',
          "department": 'Writing',
          "job": 'Writer'
        },
        {
          "adult": false,
          "gender": 2,
          "id": 198_799,
          "known_for_department": 'Acting',
          "name": 'Mark Riccardi',
          "original_name": 'Mark Riccardi',
          "popularity": 2.423,
          "profile_path": '/jKv39jzOv2fl387Gu2pQhu3wnBn.jpg',
          "credit_id": '56407f1cc3a368506d000bfb',
          "department": 'Crew',
          "job": 'Stunt Coordinator'
        },
        {
          "adult": false,
          "gender": 1,
          "id": 230_436,
          "known_for_department": 'Production',
          "name": 'Barbara Harris',
          "original_name": 'Barbara Harris',
          "popularity": 2.95,
          "profile_path": '/d1BGeZT2b81Wa9gCOPdrXGWUtmR.jpg',
          "credit_id": '5cc4cee90e0a2649cfedb0f6',
          "department": 'Production',
          "job": 'ADR Voice Casting'
        },
        {
          "adult": false,
          "gender": 0,
          "id": 1_017_376,
          "known_for_department": 'Camera',
          "name": 'Chris Squires',
          "original_name": 'Chris Squires',
          "popularity": 0.6,
          "profile_path": nil,
          "credit_id": '566aac9b92514169e2004626',
          "department": 'Camera',
          "job": 'Steadicam Operator'
        },
        {
          "adult": false,
          "gender": 1,
          "id": 1_018_788,
          "known_for_department": 'Writing',
          "name": 'Jasmine McGlade',
          "original_name": 'Jasmine McGlade',
          "popularity": 1.139,
          "profile_path": nil,
          "credit_id": '5789815c9251410db8000ab6',
          "department": 'Crew',
          "job": 'Thanks'
        },
        {
          "adult": false,
          "gender": 1,
          "id": 1_030_966,
          "known_for_department": 'Production',
          "name": 'Jeanette Volturno',
          "original_name": 'Jeanette Volturno',
          "popularity": 1.252,
          "profile_path": nil,
          "credit_id": '56407e7f9251417052000c7c',
          "department": 'Production',
          "job": 'Executive Producer'
        },
        {
          "adult": false,
          "gender": 2,
          "id": 1_049_456,
          "known_for_department": 'Sound',
          "name": 'Ben Wilkins',
          "original_name": 'Ben Wilkins',
          "popularity": 1.023,
          "profile_path": '/30VKN6GCNy9ux0BfmJ0cTo4HHQT.jpg',
          "credit_id": '566aabcc92514173830040fb',
          "department": 'Sound',
          "job": 'Supervising Sound Editor'
        },
        {
          "adult": false,
          "gender": 2,
          "id": 1_049_456,
          "known_for_department": 'Sound',
          "name": 'Ben Wilkins',
          "original_name": 'Ben Wilkins',
          "popularity": 1.023,
          "profile_path": '/30VKN6GCNy9ux0BfmJ0cTo4HHQT.jpg',
          "credit_id": '566aabbe92514173fc008d77',
          "department": 'Sound',
          "job": 'Sound Re-Recording Mixer'
        },
        {
          "adult": false,
          "gender": 2,
          "id": 1_099_700,
          "known_for_department": 'Crew',
          "name": 'Chester E. Tripp III',
          "original_name": 'Chester E. Tripp III',
          "popularity": 0.84,
          "profile_path": nil,
          "credit_id": '578922e4c3a36836c0002c11',
          "department": 'Crew',
          "job": 'Stunts'
        },
        {
          "adult": false,
          "gender": 2,
          "id": 1_125_189,
          "known_for_department": 'Production',
          "name": 'Garrick Dion',
          "original_name": 'Garrick Dion',
          "popularity": 1.306,
          "profile_path": nil,
          "credit_id": '5789153b9251411e29002aca',
          "department": 'Production',
          "job": 'Co-Producer'
        },
        {
          "adult": false,
          "gender": 2,
          "id": 1_156_888,
          "known_for_department": 'Editing',
          "name": 'Tom Cross',
          "original_name": 'Tom Cross',
          "popularity": 0.751,
          "profile_path": '/wbVgrmQKnDmBjqk0RNMgXTCE90m.jpg',
          "credit_id": '52fe4ef7c3a36847f82b3fbf',
          "department": 'Editing',
          "job": 'Editor'
        },
        {
          "adult": false,
          "gender": 1,
          "id": 1_186_280,
          "known_for_department": 'Art',
          "name": 'Melanie Jones',
          "original_name": 'Melanie Jones',
          "popularity": 0.6,
          "profile_path": nil,
          "credit_id": '54d53537c3a3683b9c00002f',
          "department": 'Art',
          "job": 'Production Design'
        },
        {
          "adult": false,
          "gender": 2,
          "id": 1_197_441,
          "known_for_department": 'Directing',
          "name": 'Nicolas Harvard',
          "original_name": 'Nicolas Harvard',
          "popularity": 0.934,
          "profile_path": nil,
          "credit_id": '5b0c03eb9251411ea001098d',
          "department": 'Directing',
          "job": 'First Assistant Director'
        },
        {
          "adult": false,
          "gender": 1,
          "id": 1_287_961,
          "known_for_department": 'Production',
          "name": 'Helen Estabrook',
          "original_name": 'Helen Estabrook',
          "popularity": 1.712,
          "profile_path": '/gudRZd8fTL1ytvQQLb6zD2Lz12Q.jpg',
          "credit_id": '52fe4ef7c3a36847f82b3fd3',
          "department": 'Production',
          "job": 'Producer'
        },
        {
          "adult": false,
          "gender": 0,
          "id": 1_319_040,
          "known_for_department": 'Production',
          "name": 'Couper Samuelson',
          "original_name": 'Couper Samuelson',
          "popularity": 0.702,
          "profile_path": nil,
          "credit_id": '56407e599251417050000bac',
          "department": 'Production',
          "job": 'Executive Producer'
        },
        {
          "adult": false,
          "gender": 2,
          "id": 1_338_158,
          "known_for_department": 'Crew',
          "name": 'John Yarbrough',
          "original_name": 'John Yarbrough',
          "popularity": 0.6,
          "profile_path": nil,
          "credit_id": '578982f5c3a36819170053c6',
          "department": 'Crew',
          "job": 'Transportation Captain'
        },
        {
          "adult": false,
          "gender": 0,
          "id": 1_358_021,
          "known_for_department": 'Visual Effects',
          "name": 'Jamison Scott Goei',
          "original_name": 'Jamison Scott Goei',
          "popularity": 0.6,
          "profile_path": nil,
          "credit_id": '566aac1992514173ff008b4b',
          "department": 'Visual Effects',
          "job": 'Visual Effects Supervisor'
        },
        {
          "adult": false,
          "gender": 0,
          "id": 1_395_180,
          "known_for_department": 'Production',
          "name": 'Stephanie Wilcox',
          "original_name": 'Stephanie Wilcox',
          "popularity": 0.6,
          "profile_path": nil,
          "credit_id": '57891621c3a36836c0002616',
          "department": 'Production',
          "job": 'Co-Producer'
        },
        {
          "adult": false,
          "gender": 1,
          "id": 1_401_855,
          "known_for_department": 'Costume & Make-Up',
          "name": 'Lisa Norcia',
          "original_name": 'Lisa Norcia',
          "popularity": 1.284,
          "profile_path": nil,
          "credit_id": '54d53592c3a3683b89000032',
          "department": 'Costume & Make-Up',
          "job": 'Costume Design'
        },
        {
          "adult": false,
          "gender": 0,
          "id": 1_401_857,
          "known_for_department": 'Production',
          "name": 'Phillip Dawe',
          "original_name": 'Phillip Dawe',
          "popularity": 1.4,
          "profile_path": nil,
          "credit_id": '56407f76c3a3685076000bdc',
          "department": 'Production',
          "job": 'Associate Producer'
        },
        {
          "adult": false,
          "gender": 0,
          "id": 1_402_475,
          "known_for_department": 'Costume & Make-Up',
          "name": 'Traci E. Smithe',
          "original_name": 'Traci E. Smithe',
          "popularity": 0.6,
          "profile_path": nil,
          "credit_id": '5640803e925141705f000bbb',
          "department": 'Costume & Make-Up',
          "job": 'Hair Department Head'
        },
        {
          "adult": false,
          "gender": 0,
          "id": 1_403_508,
          "known_for_department": 'Crew',
          "name": 'James G. Brill',
          "original_name": 'James G. Brill',
          "popularity": 0.6,
          "profile_path": nil,
          "credit_id": '57898296c3a368365d004bb4',
          "department": 'Crew',
          "job": 'Transportation Coordinator'
        },
        {
          "adult": false,
          "gender": 0,
          "id": 1_406_825,
          "known_for_department": 'Sound',
          "name": 'Craig Mann',
          "original_name": 'Craig Mann',
          "popularity": 0.923,
          "profile_path": nil,
          "credit_id": '566aabe19251417411008a5a',
          "department": 'Sound',
          "job": 'Supervising Sound Editor'
        },
        {
          "adult": false,
          "gender": 0,
          "id": 1_406_825,
          "known_for_department": 'Sound',
          "name": 'Craig Mann',
          "original_name": 'Craig Mann',
          "popularity": 0.923,
          "profile_path": nil,
          "credit_id": '566aaba8c3a3683f56003ba8',
          "department": 'Sound',
          "job": 'Sound Re-Recording Mixer'
        },
        {
          "adult": false,
          "gender": 0,
          "id": 1_411_844,
          "known_for_department": 'Camera',
          "name": 'Eric Leach',
          "original_name": 'Eric Leach',
          "popularity": 0.6,
          "profile_path": nil,
          "credit_id": '566aac80c3a3683f56003bc6',
          "department": 'Camera',
          "job": 'Camera Operator'
        },
        {
          "adult": false,
          "gender": 0,
          "id": 1_417_888,
          "known_for_department": 'Production',
          "name": 'Kandice Billingsley',
          "original_name": 'Kandice Billingsley',
          "popularity": 0.6,
          "profile_path": nil,
          "credit_id": '578980ae9251410deb0009c3',
          "department": 'Production',
          "job": 'Location Manager'
        },
        {
          "adult": false,
          "gender": 2,
          "id": 1_419_137,
          "known_for_department": 'Crew',
          "name": 'Brady Romberg',
          "original_name": 'Brady Romberg',
          "popularity": 1.663,
          "profile_path": nil,
          "credit_id": '5789226bc3a368357300278e',
          "department": 'Crew',
          "job": 'Stunts'
        },
        {
          "adult": false,
          "gender": 2,
          "id": 1_419_631,
          "known_for_department": 'Sound',
          "name": 'Justin Hurwitz',
          "original_name": 'Justin Hurwitz',
          "popularity": 2.115,
          "profile_path": '/4a03MPhWE8u0NGJF9wt0wbBcFWn.jpg',
          "credit_id": '54d5355d925141716000002a',
          "department": 'Sound',
          "job": 'Original Music Composer'
        },
        {
          "adult": false,
          "gender": 2,
          "id": 1_420_326,
          "known_for_department": 'Camera',
          "name": 'Daniel C. McFadden',
          "original_name": 'Daniel C. McFadden',
          "popularity": 0.6,
          "profile_path": nil,
          "credit_id": '5640800dc3a3685074000c5b',
          "department": 'Camera',
          "job": 'Still Photographer'
        },
        {
          "adult": false,
          "gender": 0,
          "id": 1_423_984,
          "known_for_department": 'Art',
          "name": 'Karuna Karmarkar',
          "original_name": 'Karuna Karmarkar',
          "popularity": 0.6,
          "profile_path": nil,
          "credit_id": '54d535819251416b9c00003e',
          "department": 'Art',
          "job": 'Set Decoration'
        },
        {
          "adult": false,
          "gender": 0,
          "id": 1_423_985,
          "known_for_department": 'Art',
          "name": 'Hunter Brown',
          "original_name": 'Hunter Brown',
          "popularity": 0.6,
          "profile_path": nil,
          "credit_id": '54d536529251416ba800003f',
          "department": 'Art',
          "job": 'Art Direction'
        },
        {
          "adult": false,
          "gender": 0,
          "id": 1_429_003,
          "known_for_department": 'Acting',
          "name": 'Zak Knight',
          "original_name": 'Zak Knight',
          "popularity": 0.6,
          "profile_path": nil,
          "credit_id": '566aabf6c3a36836b400843c',
          "department": 'Crew',
          "job": 'Special Effects Coordinator'
        },
        {
          "adult": false,
          "gender": 2,
          "id": 1_437_191,
          "known_for_department": 'Costume & Make-Up',
          "name": 'David Larson',
          "original_name": 'David Larson',
          "popularity": 0.6,
          "profile_path": nil,
          "credit_id": '564081549251417061000be7',
          "department": 'Costume & Make-Up',
          "job": 'Key Hair Stylist'
        },
        {
          "adult": false,
          "gender": 1,
          "id": 1_437_193,
          "known_for_department": 'Sound',
          "name": 'Lauren Hadaway',
          "original_name": 'Lauren Hadaway',
          "popularity": 2.023,
          "profile_path": '/n8yvg8bs1wNBSu3DXvWDcC68hUr.jpg',
          "credit_id": '566aab8b92514173ff008b39',
          "department": 'Sound',
          "job": 'Sound Editor'
        },
        {
          "adult": false,
          "gender": 0,
          "id": 1_443_967,
          "known_for_department": 'Editing',
          "name": 'Vahe Giragol',
          "original_name": 'Vahe Giragol',
          "popularity": 0.6,
          "profile_path": nil,
          "credit_id": '566aad6292514173ff008b71',
          "department": 'Editing',
          "job": 'Digital Intermediate'
        },
        {
          "adult": false,
          "gender": 0,
          "id": 1_450_000,
          "known_for_department": 'Directing',
          "name": 'Tracy Scott',
          "original_name": 'Tracy Scott',
          "popularity": 0.6,
          "profile_path": nil,
          "credit_id": '56407fc2c3a3685070000c78',
          "department": 'Directing',
          "job": 'Script Supervisor'
        },
        {
          "adult": false,
          "gender": 2,
          "id": 1_450_766,
          "known_for_department": 'Acting',
          "name": 'Kevin Patrick Burke',
          "original_name": 'Kevin Patrick Burke',
          "popularity": 2.823,
          "profile_path": nil,
          "credit_id": '57892242c3a368365d002605',
          "department": 'Crew',
          "job": 'Stunts'
        },
        {
          "adult": false,
          "gender": 0,
          "id": 1_451_910,
          "known_for_department": 'Art',
          "name": 'Drew Rebelein',
          "original_name": 'Drew Rebelein',
          "popularity": 0.6,
          "profile_path": nil,
          "credit_id": '566aaafcc3a36833b600483b',
          "department": 'Art',
          "job": 'Construction Coordinator'
        },
        {
          "adult": false,
          "gender": 0,
          "id": 1_453_571,
          "known_for_department": 'Acting',
          "name": 'Steven Stone',
          "original_name": 'Steven Stone',
          "popularity": 0.6,
          "profile_path": nil,
          "credit_id": '578922ab9251411e2900309c',
          "department": 'Crew',
          "job": 'Stunts'
        },
        {
          "adult": false,
          "gender": 0,
          "id": 1_525_146,
          "known_for_department": 'Art',
          "name": 'Zak Faust',
          "original_name": 'Zak Faust',
          "popularity": 0.6,
          "profile_path": nil,
          "credit_id": '566aaade9251415eed00461e',
          "department": 'Art',
          "job": 'Art Department Coordinator'
        },
        {
          "adult": false,
          "gender": 0,
          "id": 1_533_101,
          "known_for_department": 'Sound',
          "name": 'Andy Ross',
          "original_name": 'Andy Ross',
          "popularity": 0.84,
          "profile_path": nil,
          "credit_id": '56407e1d9251417057000b04',
          "department": 'Sound',
          "job": 'Music Supervisor'
        },
        {
          "adult": false,
          "gender": 2,
          "id": 1_533_516,
          "known_for_department": 'Sound',
          "name": 'Nicholas Britell',
          "original_name": 'Nicholas Britell',
          "popularity": 1.566,
          "profile_path": '/6xbBWMcup9MQlkdNvbsA4bhzYVp.jpg',
          "credit_id": '578914ce9251411e29002a94',
          "department": 'Production',
          "job": 'Co-Producer'
        },
        {
          "adult": false,
          "gender": 2,
          "id": 1_533_528,
          "known_for_department": 'Production',
          "name": 'Mark David Katchur',
          "original_name": 'Mark David Katchur',
          "popularity": 0.6,
          "profile_path": nil,
          "credit_id": '56407f389251417050000bdd',
          "department": 'Production',
          "job": 'Line Producer'
        },
        {
          "adult": false,
          "gender": 1,
          "id": 1_533_529,
          "known_for_department": 'Production',
          "name": 'Sarah Domeier Lindo',
          "original_name": 'Sarah Domeier Lindo',
          "popularity": 2.705,
          "profile_path": nil,
          "credit_id": '56407feac3a3685059000cb9',
          "department": 'Production',
          "job": 'Casting Associate'
        },
        {
          "adult": false,
          "gender": 0,
          "id": 1_533_530,
          "known_for_department": 'Lighting',
          "name": 'Elan Yaari',
          "original_name": 'Elan Yaari',
          "popularity": 0.828,
          "profile_path": nil,
          "credit_id": '56407ffbc3a368506d000c25',
          "department": 'Lighting',
          "job": 'Gaffer'
        },
        {
          "adult": false,
          "gender": 2,
          "id": 1_547_656,
          "known_for_department": 'Sound',
          "name": 'Joe Schiff',
          "original_name": 'Joe Schiff',
          "popularity": 1.018,
          "profile_path": nil,
          "credit_id": '5b0c03c10e0a260df2015bd9',
          "department": 'Sound',
          "job": 'Dialogue Editor'
        },
        {
          "adult": false,
          "gender": 0,
          "id": 1_547_657,
          "known_for_department": 'Sound',
          "name": 'Alicia Hadaway',
          "original_name": 'Alicia Hadaway',
          "popularity": 0.6,
          "profile_path": nil,
          "credit_id": '5b0c0541c3a3684af5019ead',
          "department": 'Sound',
          "job": 'Foley Artist'
        },
        {
          "adult": false,
          "gender": 2,
          "id": 1_547_658,
          "known_for_department": 'Visual Effects',
          "name": 'David Lebensfeld',
          "original_name": 'David Lebensfeld',
          "popularity": 0.6,
          "profile_path": nil,
          "credit_id": '566aac2f9251417383004113',
          "department": 'Visual Effects',
          "job": 'Visual Effects Supervisor'
        },
        {
          "adult": false,
          "gender": 0,
          "id": 1_547_659,
          "known_for_department": 'Visual Effects',
          "name": 'Grant Miller',
          "original_name": 'Grant Miller',
          "popularity": 0.6,
          "profile_path": nil,
          "credit_id": '566aac4b92514173fc008d92',
          "department": 'Visual Effects',
          "job": 'Visual Effects Supervisor'
        },
        {
          "adult": false,
          "gender": 0,
          "id": 1_547_660,
          "known_for_department": 'Editing',
          "name": 'Steve Hernandez',
          "original_name": 'Steve Hernandez',
          "popularity": 0.6,
          "profile_path": nil,
          "credit_id": '566aad3dc3a368264700402e',
          "department": 'Editing',
          "job": 'Digital Intermediate'
        },
        {
          "adult": false,
          "gender": 0,
          "id": 1_547_661,
          "known_for_department": 'Editing',
          "name": 'Mike Will',
          "original_name": 'Mike Will',
          "popularity": 0.6,
          "profile_path": nil,
          "credit_id": '566aad8192514169e200463c',
          "department": 'Editing',
          "job": 'Digital Intermediate'
        },
        {
          "adult": false,
          "gender": 0,
          "id": 1_547_662,
          "known_for_department": 'Editing',
          "name": 'John To',
          "original_name": 'John To',
          "popularity": 0.6,
          "profile_path": nil,
          "credit_id": '566aad9dc3a3682e98003e54',
          "department": 'Editing',
          "job": 'First Assistant Editor'
        },
        {
          "adult": false,
          "gender": 2,
          "id": 2_052_395,
          "known_for_department": 'Sound',
          "name": 'Thomas Curley',
          "original_name": 'Thomas Curley',
          "popularity": 0.6,
          "profile_path": nil,
          "credit_id": '5b0c056ec3a3684af5019ecb',
          "department": 'Sound',
          "job": 'Production Sound Mixer'
        },
        {
          "adult": false,
          "gender": 0,
          "id": 2_069_689,
          "known_for_department": 'Art',
          "name": 'Chris Maxson',
          "original_name": 'Chris Maxson',
          "popularity": 0.6,
          "profile_path": nil,
          "credit_id": '61744d8a0d5d85002aebf315',
          "department": 'Art',
          "job": 'Set Dresser'
        },
        {
          "adult": false,
          "gender": 0,
          "id": 2_237_849,
          "known_for_department": 'Art',
          "name": 'Tim Dodge',
          "original_name": 'Tim Dodge',
          "popularity": 0.6,
          "profile_path": nil,
          "credit_id": '61744d783f4833009049dedd',
          "department": 'Art',
          "job": 'Set Dresser'
        }
      ]
    }

    movie = Movie.new(details_data, reviews_data, credits_data)

    expect(movie).to be_a Movie
    expect(movie.poster).to eq details_data[:poster_path]
    expect(movie.title).to eq details_data[:original_title]
  end
end
